### ISSUE TITLE
Implement fragment-dependent cache invalidation in Sphinx for RST documents using the extension

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/sphinxcontrib-towncrier#1]
To speed-up sequential builds, Sphinx caches documents as doctrees. This cache is based on whether the tracked RST files have changed and does not know anything about the changes in the directive output.
So including this directive into the document may result in it not picking up the new change fragments.

We need to explicitly document this and add some pointers on how to force rebuilds.

This idea is coming from https://github.com/ansible/pylibssh/issues/120 as reported by @ewjoachim.

**Comment by ewjoachim** [comment]
Note: if anyone finds a smart idea for this, I'll definitely steal it in https://github.com/peopledoc/sphinx-github-changelog and vice versa.

(and I'm convinced there's a technical way of handling this, not just reminding the user to make the job of the computer :) )

**Comment by webknjaz** [comment]
Ref: https://github.com/sphinx-doc/sphinx/issues/8040

**Comment by ewjoachim** [comment]
https://www.sphinx-doc.org/en/master/extdev/envapi.html?highlight=note_dependency#sphinx.environment.BuildEnvironment.note_dependency \o/

**Comment by webknjaz** [comment]
@ewjoachim interesting... But how would sphinx know that this is connected to a directive in a certain file? I thought we need to point it to the document that uses the directive.

**Comment by ewjoachim** [comment]
No, this is done in the directive code itself, so Sphinx knows where it is.

**Comment by ewjoachim** [comment]
Fact is we could have multiple directive, each pointing to a different towncrier config and this would still work

**Comment by webknjaz** [comment]
Nice! Although, the current implementation has one global setting for the towncrier config and I don't think that one project would need more (unless it's a monorepo, I guess, but then the docs would likely be separate anyway).

P.S. The main Towncrier CLI only supports custom config in their repo master, not in the released version so it's all only theoretical atm.

**Comment by webknjaz** [comment]
FTR the approach with `note_dependency()` wouldn't work because we need to inject this outside of the directive from the new files that appear after the cache already exists. I've added some comments in #23.
