### ISSUE TITLE
⚙ Configure pre-commit tool

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/sphinxcontrib-towncrier#16]
We can now start configuring linting-related things.

Please take as a base these:
- https://github.com/ansible/pylibssh/blob/devel/.pre-commit-config.yaml
- https://github.com/ansible/ansible-lint/blob/master/.pre-commit-config.yaml#L37-L43
- https://github.com/ansible/ansible-lint/blob/master/.yamllint (but turn `consistent` to `false`)
- https://github.com/ansible/pylibssh/blob/devel/.darglint
- https://github.com/ansible/pylibssh/blob/devel/.isort.cfg
- https://github.com/ansible/pylibssh/blob/devel/.flake8
- https://github.com/ansible/ansible-lint/blob/master/mypy.ini / https://github.com/sanitizers/octomachinery/blob/master/mypy.ini / https://github.com/ansible/ansible-lint/blob/master/.pre-commit-config.yaml#L60-L67
- https://github.com/ansible/ansible-lint/blob/master/.pre-commit-config.yaml#L68-L71 / https://github.com/sanitizers/octomachinery/blob/master/.pre-commit-config.yaml#L51-L58 / https://github.com/sanitizers/octomachinery/blob/master/.pylintrc (generate the base config via `pylint --generate-rcfile > .pylintrc` and only then borrow things from examples, only if necessary, in separate commits, for comparison)

Since it's a lot of changes, feel free to submit separate PRs with small changes.

**Comment by webknjaz** [comment]
The example configs cap isort below v5 for flake8 but I think we can try pinning flake8-isort to use the new alpha version: https://github.com/gforcada/flake8-isort/pull/92#issuecomment-670480995.

**Comment by slsh1o** [comment]
TODO list:
- [ ] add-trailing-comma

- [ ] base pre-commit-hooks

- [ ] pre-commit-hooks-markup

- [ ] pydocstyle

- [ ] yamllint

- [ ] pylint (local)

- [ ] darglint

- [ ] isort (hook & config)

- [ ] flake8

- [ ] mypy

- [ ]
