### ISSUE TITLE
0.2.0a0: no docs/ in pypi dist tar ball

### ISSUE THREAD

**Issue by kloczek** [sphinx-contrib/sphinxcontrib-towncrier#51]
Looks like docs/ content is not included in pypi dist tar ball.

**Comment by webknjaz** [comment]
This is because they were added to the repo after the last tag. Wait for the next release.

**Comment by kloczek** [comment]
Aa ... ok :)
May as when you plan next release? :)

**Comment by webknjaz** [comment]
I don't plan any for now. Maybe when I'll invent something to deal with the draft bug in towncrier itself.

**Comment by kloczek** [comment]
Provide documentation is IMO good enough reason to make new release :)

**Comment by webknjaz** [comment]
Having time to catch up with all the projects is as well.
