### ISSUE TITLE
Allow lower version of importlib_metadata

### ISSUE THREAD

**Issue by kasium** [sphinx-contrib/sphinxcontrib-towncrier#67]
As you might aware, flake8 pins the version of importlib_metadata to importlib-metadata<4.3 for python 3.7 with no plan to remove this. As far as I can see, you only use it for "version", so could you relax the minimal version required?

I'm happy to provide a PR for this

**Comment by webknjaz** [comment]
Interesting... I wasn't aware of the drama @ https://github.com/PyCQA/flake8/commit/975a3f45334861ebd8960c00e881443c23654bca.
Let me try to do some Git archeology to see why I limited the dependency here.

**Comment by webknjaz** [comment]
Hm... It was added one and a half months ago at https://github.com/sphinx-contrib/sphinxcontrib-towncrier/commit/0b4718a10b9d07fddec207ed98c16a917ba84a42#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R56 but there's nothing specific in the commit message.
But! There must be a reason I've set a specific patch version as the minimum one. Let me check out the changelog over there..

**Comment by webknjaz** [comment]
I don't see a specific reason to have that lower boundary. So maybe we could even drop the lower limit.

@kasium if you're up to it, file a PR, see if the tests pass. And maybe set it to a much older version locally (without committing), and run the tests under Python 3.6 and 3.7 to see if there's anything breaking there.

**Comment by kasium** [comment]
@webknjaz can you please consider to push a release?

**Comment by webknjaz** [comment]
@kasium I've just triggered the release workflow: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/actions/runs/3396625453. It'll take some time until it gets to the publish job.

**Comment by kasium** [comment]
Thanks a lot!

**Comment by webknjaz** [comment]
v0.3.1a0 is out: https://pypi.org/project/sphinxcontrib-towncrier/0.3.1a0/
Feedback page: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/discussions/71
