### ISSUE TITLE
Dict-access to towncrier's Config objects breaks with Towncrier 22.12

### ISSUE THREAD

**Issue by hynek** [sphinx-contrib/sphinxcontrib-towncrier#76]
See https://github.com/twisted/towncrier/issues/461 or https://github.com/python-attrs/attrs/actions/runs/3755544183/jobs/6380710259#step:7:39

Config has become a data class in the last release and it's all my fault, sorry.

https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/12362b595bfe896e0846072b172dc106cac18349/src/sphinxcontrib/towncrier/ext.py#L132-L143

**Comment by adiroiban** [comment]
I don't think that for the Towncrier configuration , we made any commitment for a stable API

I can see that this extension uses a towncrier helper that is imported from a private package.

https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/12362b595bfe896e0846072b172dc106cac18349/src/sphinxcontrib/towncrier/_towncrier.py#L7-L18

I don't think that we need to worry too much.

This is a developer tool and I hope that nobody is using Towcrier to implement any critical system.
By critical system I mean one for which if the latest towncrier breaks, someone will die :)

**Comment by webknjaz** [comment]
Ack: #75

**Comment by davfsa** [comment]
@webknjaz would it be possible to make a release soon-ish?

Thank you in advance for getting the bug fixed so quickly!

**Comment by webknjaz** [comment]
Have fun! https://github.com/sphinx-contrib/sphinxcontrib-towncrier/releases/tag/v0.3.2a0

**Comment by hynek** [comment]
awesome, thanks!
