### ISSUE TITLE
Support finding `towncrier.toml` automatically

### ISSUE THREAD

**Issue by HealthyPear** [sphinx-contrib/sphinxcontrib-towncrier#81]
The configuration of towncrier can also be placed in a dedicated configuration file named `towncrier.toml` with the same syntax, which is meant to be stored in the same place of `pyproject.toml` and takes precedence over it.

It seems to me that this package doesn't respect this, and looks only at `pyproject.toml`:

> WARNING: Missing key 'towncrier' in file XXXX/docs/source/../../pyproject.toml

**Comment by HealthyPear** [comment]
https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/098c78169e15465531bc03e10bc42d4827d265d9/src/sphinxcontrib/towncrier/ext.py#L109

**Comment by webknjaz** [comment]
This is a great idea, a PR is welcome!
Note that you should be able to pass a full path to the towncrier config via `conf.py` IIRC. I don't remember the details, though.. Somebody would need to dig into the source code.

**Comment by webknjaz** [comment]
> https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/098c78169e15465531bc03e10bc42d4827d265d9/src/sphinxcontrib/towncrier/ext.py#L109

@HealthyPear if you look one line below, you'll see that's redefined with an incoming setting, so it should be possible to set up `towncrier_draft_config_path = 'towncrier.toml'` in `conf.py` ­— that should work.

Though, you're right, and it'd be nice to have this Sphinx extension find it automatically…

**Comment by jaraco** [comment]
This issue also affects Setuptools now that jaraco/skeleton is adopting towncrier.

**Comment by webknjaz** [comment]
Have you tried the workaround above? I'm on vacation this week so won't be able to look into it right now.

**Comment by HealthyPear** [comment]
@webknjaz sorry for the big delay on this: I can confirm that your suggested workaround works!

It is true that this should be caught automatically, but since it's a configurable option I think this is sufficient (though it should be added to the documentation).

**Comment by jaraco** [comment]
Unfortunately, it looks like [towncrier doesn't expose the config file discovery](https://github.com/twisted/towncrier/blob/806bec1248b0ea8b86db21e0ce90b1849d3cd721/src/towncrier/_settings/load.py#L86-L95) without also parsing the config, meaning this project will necessarily have to provide its own copy of the logic.
