### ISSUE TITLE
Rename this repo to towncrier?

### ISSUE THREAD

**Issue by Freed-Wu** [sphinx-contrib/sphinxcontrib-towncrier#87]
According to <https://github.com/sphinx-contrib/github-administration>:

> rename the repository to remove prefixes like sphinx, sphinx-contrib, and sphinxcontrib. Don't forget to update the documentation in the repository, too!

**Comment by webknjaz** [comment]
That was the original name and many people (not me!) wanted it prefixed. The reasoning was that it could be confused with the towncrier project IIRC. But also, when people make forks, their forked repo name doesn't preserve the org name, unless they manually edit it. This also leads to similar confusion.
While I like this idea a lot, we must respect other people's options 🤷‍♂️.

**Comment by webknjaz** [comment]
Here, @dhellmann granted us an exception: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/5#issuecomment-668601345

**Comment by Freed-Wu** [comment]
OK, advise to pin #5 for visibility :smile:

**Comment by webknjaz** [comment]
I don't think any of the end-users would care about the repo name. In 3 years, nobody asked a question about it. It's too rare for such a pin to the useful, objectively.
